# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from google.pubsub.v1 import schema_pb2 as google_dot_pubsub_dot_v1_dot_schema__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in google/pubsub/v1/schema_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class SchemaServiceStub(object):
    """Service for doing schema-related operations.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateSchema = channel.unary_unary(
                '/google.pubsub.v1.SchemaService/CreateSchema',
                request_serializer=google_dot_pubsub_dot_v1_dot_schema__pb2.CreateSchemaRequest.SerializeToString,
                response_deserializer=google_dot_pubsub_dot_v1_dot_schema__pb2.Schema.FromString,
                _registered_method=True)
        self.GetSchema = channel.unary_unary(
                '/google.pubsub.v1.SchemaService/GetSchema',
                request_serializer=google_dot_pubsub_dot_v1_dot_schema__pb2.GetSchemaRequest.SerializeToString,
                response_deserializer=google_dot_pubsub_dot_v1_dot_schema__pb2.Schema.FromString,
                _registered_method=True)
        self.ListSchemas = channel.unary_unary(
                '/google.pubsub.v1.SchemaService/ListSchemas',
                request_serializer=google_dot_pubsub_dot_v1_dot_schema__pb2.ListSchemasRequest.SerializeToString,
                response_deserializer=google_dot_pubsub_dot_v1_dot_schema__pb2.ListSchemasResponse.FromString,
                _registered_method=True)
        self.ListSchemaRevisions = channel.unary_unary(
                '/google.pubsub.v1.SchemaService/ListSchemaRevisions',
                request_serializer=google_dot_pubsub_dot_v1_dot_schema__pb2.ListSchemaRevisionsRequest.SerializeToString,
                response_deserializer=google_dot_pubsub_dot_v1_dot_schema__pb2.ListSchemaRevisionsResponse.FromString,
                _registered_method=True)
        self.CommitSchema = channel.unary_unary(
                '/google.pubsub.v1.SchemaService/CommitSchema',
                request_serializer=google_dot_pubsub_dot_v1_dot_schema__pb2.CommitSchemaRequest.SerializeToString,
                response_deserializer=google_dot_pubsub_dot_v1_dot_schema__pb2.Schema.FromString,
                _registered_method=True)
        self.RollbackSchema = channel.unary_unary(
                '/google.pubsub.v1.SchemaService/RollbackSchema',
                request_serializer=google_dot_pubsub_dot_v1_dot_schema__pb2.RollbackSchemaRequest.SerializeToString,
                response_deserializer=google_dot_pubsub_dot_v1_dot_schema__pb2.Schema.FromString,
                _registered_method=True)
        self.DeleteSchemaRevision = channel.unary_unary(
                '/google.pubsub.v1.SchemaService/DeleteSchemaRevision',
                request_serializer=google_dot_pubsub_dot_v1_dot_schema__pb2.DeleteSchemaRevisionRequest.SerializeToString,
                response_deserializer=google_dot_pubsub_dot_v1_dot_schema__pb2.Schema.FromString,
                _registered_method=True)
        self.DeleteSchema = channel.unary_unary(
                '/google.pubsub.v1.SchemaService/DeleteSchema',
                request_serializer=google_dot_pubsub_dot_v1_dot_schema__pb2.DeleteSchemaRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)
        self.ValidateSchema = channel.unary_unary(
                '/google.pubsub.v1.SchemaService/ValidateSchema',
                request_serializer=google_dot_pubsub_dot_v1_dot_schema__pb2.ValidateSchemaRequest.SerializeToString,
                response_deserializer=google_dot_pubsub_dot_v1_dot_schema__pb2.ValidateSchemaResponse.FromString,
                _registered_method=True)
        self.ValidateMessage = channel.unary_unary(
                '/google.pubsub.v1.SchemaService/ValidateMessage',
                request_serializer=google_dot_pubsub_dot_v1_dot_schema__pb2.ValidateMessageRequest.SerializeToString,
                response_deserializer=google_dot_pubsub_dot_v1_dot_schema__pb2.ValidateMessageResponse.FromString,
                _registered_method=True)


class SchemaServiceServicer(object):
    """Service for doing schema-related operations.
    """

    def CreateSchema(self, request, context):
        """Creates a schema.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetSchema(self, request, context):
        """Gets a schema.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListSchemas(self, request, context):
        """Lists schemas in a project.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListSchemaRevisions(self, request, context):
        """Lists all schema revisions for the named schema.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CommitSchema(self, request, context):
        """Commits a new schema revision to an existing schema.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RollbackSchema(self, request, context):
        """Creates a new schema revision that is a copy of the provided revision_id.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteSchemaRevision(self, request, context):
        """Deletes a specific schema revision.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteSchema(self, request, context):
        """Deletes a schema.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ValidateSchema(self, request, context):
        """Validates a schema.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ValidateMessage(self, request, context):
        """Validates a message against a schema.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SchemaServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateSchema': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateSchema,
                    request_deserializer=google_dot_pubsub_dot_v1_dot_schema__pb2.CreateSchemaRequest.FromString,
                    response_serializer=google_dot_pubsub_dot_v1_dot_schema__pb2.Schema.SerializeToString,
            ),
            'GetSchema': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSchema,
                    request_deserializer=google_dot_pubsub_dot_v1_dot_schema__pb2.GetSchemaRequest.FromString,
                    response_serializer=google_dot_pubsub_dot_v1_dot_schema__pb2.Schema.SerializeToString,
            ),
            'ListSchemas': grpc.unary_unary_rpc_method_handler(
                    servicer.ListSchemas,
                    request_deserializer=google_dot_pubsub_dot_v1_dot_schema__pb2.ListSchemasRequest.FromString,
                    response_serializer=google_dot_pubsub_dot_v1_dot_schema__pb2.ListSchemasResponse.SerializeToString,
            ),
            'ListSchemaRevisions': grpc.unary_unary_rpc_method_handler(
                    servicer.ListSchemaRevisions,
                    request_deserializer=google_dot_pubsub_dot_v1_dot_schema__pb2.ListSchemaRevisionsRequest.FromString,
                    response_serializer=google_dot_pubsub_dot_v1_dot_schema__pb2.ListSchemaRevisionsResponse.SerializeToString,
            ),
            'CommitSchema': grpc.unary_unary_rpc_method_handler(
                    servicer.CommitSchema,
                    request_deserializer=google_dot_pubsub_dot_v1_dot_schema__pb2.CommitSchemaRequest.FromString,
                    response_serializer=google_dot_pubsub_dot_v1_dot_schema__pb2.Schema.SerializeToString,
            ),
            'RollbackSchema': grpc.unary_unary_rpc_method_handler(
                    servicer.RollbackSchema,
                    request_deserializer=google_dot_pubsub_dot_v1_dot_schema__pb2.RollbackSchemaRequest.FromString,
                    response_serializer=google_dot_pubsub_dot_v1_dot_schema__pb2.Schema.SerializeToString,
            ),
            'DeleteSchemaRevision': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteSchemaRevision,
                    request_deserializer=google_dot_pubsub_dot_v1_dot_schema__pb2.DeleteSchemaRevisionRequest.FromString,
                    response_serializer=google_dot_pubsub_dot_v1_dot_schema__pb2.Schema.SerializeToString,
            ),
            'DeleteSchema': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteSchema,
                    request_deserializer=google_dot_pubsub_dot_v1_dot_schema__pb2.DeleteSchemaRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'ValidateSchema': grpc.unary_unary_rpc_method_handler(
                    servicer.ValidateSchema,
                    request_deserializer=google_dot_pubsub_dot_v1_dot_schema__pb2.ValidateSchemaRequest.FromString,
                    response_serializer=google_dot_pubsub_dot_v1_dot_schema__pb2.ValidateSchemaResponse.SerializeToString,
            ),
            'ValidateMessage': grpc.unary_unary_rpc_method_handler(
                    servicer.ValidateMessage,
                    request_deserializer=google_dot_pubsub_dot_v1_dot_schema__pb2.ValidateMessageRequest.FromString,
                    response_serializer=google_dot_pubsub_dot_v1_dot_schema__pb2.ValidateMessageResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'google.pubsub.v1.SchemaService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('google.pubsub.v1.SchemaService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class SchemaService(object):
    """Service for doing schema-related operations.
    """

    @staticmethod
    def CreateSchema(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/google.pubsub.v1.SchemaService/CreateSchema',
            google_dot_pubsub_dot_v1_dot_schema__pb2.CreateSchemaRequest.SerializeToString,
            google_dot_pubsub_dot_v1_dot_schema__pb2.Schema.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetSchema(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/google.pubsub.v1.SchemaService/GetSchema',
            google_dot_pubsub_dot_v1_dot_schema__pb2.GetSchemaRequest.SerializeToString,
            google_dot_pubsub_dot_v1_dot_schema__pb2.Schema.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListSchemas(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/google.pubsub.v1.SchemaService/ListSchemas',
            google_dot_pubsub_dot_v1_dot_schema__pb2.ListSchemasRequest.SerializeToString,
            google_dot_pubsub_dot_v1_dot_schema__pb2.ListSchemasResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListSchemaRevisions(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/google.pubsub.v1.SchemaService/ListSchemaRevisions',
            google_dot_pubsub_dot_v1_dot_schema__pb2.ListSchemaRevisionsRequest.SerializeToString,
            google_dot_pubsub_dot_v1_dot_schema__pb2.ListSchemaRevisionsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CommitSchema(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/google.pubsub.v1.SchemaService/CommitSchema',
            google_dot_pubsub_dot_v1_dot_schema__pb2.CommitSchemaRequest.SerializeToString,
            google_dot_pubsub_dot_v1_dot_schema__pb2.Schema.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RollbackSchema(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/google.pubsub.v1.SchemaService/RollbackSchema',
            google_dot_pubsub_dot_v1_dot_schema__pb2.RollbackSchemaRequest.SerializeToString,
            google_dot_pubsub_dot_v1_dot_schema__pb2.Schema.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteSchemaRevision(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/google.pubsub.v1.SchemaService/DeleteSchemaRevision',
            google_dot_pubsub_dot_v1_dot_schema__pb2.DeleteSchemaRevisionRequest.SerializeToString,
            google_dot_pubsub_dot_v1_dot_schema__pb2.Schema.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteSchema(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/google.pubsub.v1.SchemaService/DeleteSchema',
            google_dot_pubsub_dot_v1_dot_schema__pb2.DeleteSchemaRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ValidateSchema(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/google.pubsub.v1.SchemaService/ValidateSchema',
            google_dot_pubsub_dot_v1_dot_schema__pb2.ValidateSchemaRequest.SerializeToString,
            google_dot_pubsub_dot_v1_dot_schema__pb2.ValidateSchemaResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ValidateMessage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/google.pubsub.v1.SchemaService/ValidateMessage',
            google_dot_pubsub_dot_v1_dot_schema__pb2.ValidateMessageRequest.SerializeToString,
            google_dot_pubsub_dot_v1_dot_schema__pb2.ValidateMessageResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
