-- rediswire (Redis frontend) store, StoreType.REDIS. Every redis-enabled Postgres host gets all tables; a key lives
-- on the shard owning its hash slot (CRC16 like Redis Cluster). `db` is the numeric SELECT database (namespace).
-- Child tables reference warp_redis_keys with ON DELETE CASCADE / ON UPDATE CASCADE (RENAME is one UPDATE), and a
-- trigger clears the children when a key's TYPE changes (SET over a hash, ...). Expiry: `exp` = epoch ms, a row is
-- dead once exp <= now; `n` counts the elements of a container key (kept by every mutation, so HLEN/LLEN/SCARD/ZCARD/XLEN are O(1)); reads filter it, writes purge it, a sweeper deletes it.
-- ### version sequence
CREATE SEQUENCE IF NOT EXISTS warp_redis_ver
-- ### keys
CREATE TABLE IF NOT EXISTS warp_redis_keys (
    db   INT NOT NULL,
    k    BYTEA NOT NULL,
    type SMALLINT NOT NULL,
    exp  BIGINT,
    ver  BIGINT NOT NULL DEFAULT nextval('warp_redis_ver'),
    slot INT NOT NULL DEFAULT 0,
    sv   BYTEA,
    n    BIGINT NOT NULL DEFAULT 0,
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY,
    PRIMARY KEY (db, k)
)
-- ### keys scan index (stateless SCAN cursors)
CREATE UNIQUE INDEX IF NOT EXISTS warp_redis_keys_id ON warp_redis_keys (id)
-- ### keys expiry index
CREATE INDEX IF NOT EXISTS warp_redis_keys_exp ON warp_redis_keys (exp) WHERE exp IS NOT NULL
-- ### hashes
CREATE TABLE IF NOT EXISTS warp_redis_hashes (
    db INT NOT NULL, k BYTEA NOT NULL, f BYTEA NOT NULL, v BYTEA NOT NULL,
    PRIMARY KEY (db, k, f),
    FOREIGN KEY (db, k) REFERENCES warp_redis_keys (db, k) ON DELETE CASCADE ON UPDATE CASCADE
)
-- ### lists
CREATE TABLE IF NOT EXISTS warp_redis_lists (
    db INT NOT NULL, k BYTEA NOT NULL, pos BIGINT NOT NULL, v BYTEA NOT NULL,
    PRIMARY KEY (db, k, pos),
    FOREIGN KEY (db, k) REFERENCES warp_redis_keys (db, k) ON DELETE CASCADE ON UPDATE CASCADE
)
-- ### sets
CREATE TABLE IF NOT EXISTS warp_redis_sets (
    db INT NOT NULL, k BYTEA NOT NULL, m BYTEA NOT NULL,
    PRIMARY KEY (db, k, m),
    FOREIGN KEY (db, k) REFERENCES warp_redis_keys (db, k) ON DELETE CASCADE ON UPDATE CASCADE
)
-- ### zsets
CREATE TABLE IF NOT EXISTS warp_redis_zsets (
    db INT NOT NULL, k BYTEA NOT NULL, m BYTEA NOT NULL, score DOUBLE PRECISION NOT NULL,
    PRIMARY KEY (db, k, m),
    FOREIGN KEY (db, k) REFERENCES warp_redis_keys (db, k) ON DELETE CASCADE ON UPDATE CASCADE
)
-- ### zsets score index
CREATE INDEX IF NOT EXISTS warp_redis_zsets_score ON warp_redis_zsets (db, k, score, m)
-- ### stream entries
CREATE TABLE IF NOT EXISTS warp_redis_stream_entries (
    db INT NOT NULL, k BYTEA NOT NULL, ms BIGINT NOT NULL, seq BIGINT NOT NULL, f BYTEA NOT NULL,
    PRIMARY KEY (db, k, ms, seq),
    FOREIGN KEY (db, k) REFERENCES warp_redis_keys (db, k) ON DELETE CASCADE ON UPDATE CASCADE
)
-- ### stream groups
CREATE TABLE IF NOT EXISTS warp_redis_stream_groups (
    db INT NOT NULL, k BYTEA NOT NULL, g BYTEA NOT NULL, last_ms BIGINT NOT NULL, last_seq BIGINT NOT NULL,
    entries_read BIGINT,
    PRIMARY KEY (db, k, g),
    FOREIGN KEY (db, k) REFERENCES warp_redis_keys (db, k) ON DELETE CASCADE ON UPDATE CASCADE
)
-- ### stream consumers
CREATE TABLE IF NOT EXISTS warp_redis_stream_consumers (
    db INT NOT NULL, k BYTEA NOT NULL, g BYTEA NOT NULL, c BYTEA NOT NULL, seen BIGINT NOT NULL, active BIGINT NOT NULL DEFAULT -1,
    PRIMARY KEY (db, k, g, c),
    FOREIGN KEY (db, k, g) REFERENCES warp_redis_stream_groups (db, k, g) ON DELETE CASCADE ON UPDATE CASCADE
)
-- ### stream pending entries
CREATE TABLE IF NOT EXISTS warp_redis_stream_pel (
    db INT NOT NULL, k BYTEA NOT NULL, g BYTEA NOT NULL, ms BIGINT NOT NULL, seq BIGINT NOT NULL,
    c BYTEA NOT NULL, delivered BIGINT NOT NULL, cnt INT NOT NULL DEFAULT 1,
    PRIMARY KEY (db, k, g, ms, seq),
    FOREIGN KEY (db, k, g) REFERENCES warp_redis_stream_groups (db, k, g) ON DELETE CASCADE ON UPDATE CASCADE
)
-- ### stream pending by consumer
CREATE INDEX IF NOT EXISTS warp_redis_stream_pel_c ON warp_redis_stream_pel (db, k, g, c)
-- ### pubsub overflow (messages too large for a NOTIFY payload)
CREATE TABLE IF NOT EXISTS warp_redis_pubsub (
    id BIGSERIAL PRIMARY KEY, ts TIMESTAMPTZ NOT NULL DEFAULT now(), ch BYTEA NOT NULL, msg BYTEA NOT NULL
)
-- ### type change cleanup function
CREATE OR REPLACE FUNCTION warp_redis_keys_typechange() RETURNS trigger AS $$
BEGIN
    CASE OLD.type
        WHEN 1 THEN DELETE FROM warp_redis_hashes WHERE db = OLD.db AND k = OLD.k;
        WHEN 2 THEN DELETE FROM warp_redis_lists WHERE db = OLD.db AND k = OLD.k;
        WHEN 3 THEN DELETE FROM warp_redis_sets WHERE db = OLD.db AND k = OLD.k;
        WHEN 4 THEN DELETE FROM warp_redis_zsets WHERE db = OLD.db AND k = OLD.k;
        WHEN 5 THEN DELETE FROM warp_redis_stream_entries WHERE db = OLD.db AND k = OLD.k;
                    DELETE FROM warp_redis_stream_groups WHERE db = OLD.db AND k = OLD.k;
        ELSE NULL;
    END CASE;
    RETURN NEW;
END
$$ LANGUAGE plpgsql
-- ### type change trigger (drop)
DROP TRIGGER IF EXISTS warp_redis_keys_typechange ON warp_redis_keys
-- ### type change trigger
CREATE TRIGGER warp_redis_keys_typechange BEFORE UPDATE OF type ON warp_redis_keys
    FOR EACH ROW WHEN (OLD.type IS DISTINCT FROM NEW.type) EXECUTE FUNCTION warp_redis_keys_typechange()
