"""Documented differences from real Neo4j that the differential corpus may keep showing (case name -> reason).
Everything else must match the recorded oracle output exactly."""

KNOWN = {
    "proc/db_ping": "db.ping is not a procedure of Neo4j 5.26 community; Warp answers it",
    "proc/show_databases": "SHOW DATABASES lists the two static databases; attribute columns differ",
    "proc/show_current_user_absent": "security commands (SHOW CURRENT USER, users, roles) are not implemented",
    "proc/create_database": "multi-database administration is not supported: a Warp backend is the database",
    "proc/load_csv": "LOAD CSV is not supported",
    "proc/explain_query": "EXPLAIN / PROFILE plans are not produced",
    "ddl/fulltext_index": "full-text indexes are not supported",
    "ddl/rel_index": "relationship-property indexes are not implemented",
    "ddl/rel_unique_constraint": "relationship-property constraints are not implemented",
    "tx/timeout_exceeded": "timeout is checked between rows/clauses; error code text may differ",
    "meta/database_unknown": "an unmatched Bolt db name routes to the default backend unless strict routing rejects it",
    "expr/time/localtime_map": "Warp accepts sub-second fields without a second component (Neo4j rejects it)",
    "expr/time/date_epoch_days": "unknown temporal accessors yield null in Warp (Neo4j raises a TypeError)",
    "g/match/shortest_same": "shortestPath from a node to itself: Neo4j raises an error, Warp returns no path",
    "g/match/keys_fn": "property key order: keys()/properties() list keys in jsonb order (length, then alphabetical), not creation order",
    "g/match/pattern_comprehension": "relationship enumeration order without ORDER BY is not the creation order Neo4j happens to return",
    "g/agg/agg_where": "aggregate in WHERE: Warp reports a SyntaxError at compile time, Neo4j an execution failure",
    "ddl/create_data_and_schema_same_tx": "Warp allows data and schema changes in one transaction (Neo4j forbids it)",
    "meta/database_system": "the system database is not addressable as a query target",
    "param/roundtrip_list_mixed": "valueType() of heterogeneous lists prints LIST<ANY> instead of Neo4j's union type",
    "param/roundtrip_list_nested": "valueType() of nested lists prints LIST<ANY> instead of Neo4j's inferred element type",
    "param/roundtrip_bytes_empty": "valueType() of a byte array is ANY (Neo4j reports LIST<INTEGER NOT NULL>)",
    "param/roundtrip_bytes_small": "valueType() of a byte array is ANY (Neo4j reports LIST<INTEGER NOT NULL>)",
    "param/roundtrip_bytes_300": "valueType() of a byte array is ANY (Neo4j reports LIST<INTEGER NOT NULL>)",
    "param/roundtrip_bytes_70k": "valueType() of a byte array is ANY (Neo4j reports LIST<INTEGER NOT NULL>)",
    "param/store_bytes": "valueType() of a stored byte array is ANY (Neo4j reports LIST<INTEGER NOT NULL>)",
    "g/match/type_alt_colon": "`[:A|:B]` (colon after the bar) is accepted by Warp; Neo4j 5.26 only accepts it in some positions",
    "g/agg/percentile_bad": "percentile out of range: ArgumentError in Warp, SyntaxError for literal arguments in Neo4j",
    "expr/str/toString_list": "toString([...]) is a runtime TypeError in Warp, a compile-time SyntaxError in Neo4j",
}
