# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import warp_pb2 as warp__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in warp_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class QueryServiceStub(object):
    """Native Warp wire protocol: a thin Type-3 JDBC driver talks this
    instead of emulating a foreign database's wire protocol. Stateless per
    call — username/password travel on every request rather than a separate
    session-establishing RPC, keeping the server side simple (no
    session/stream bookkeeping) for this first narrow slice.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Execute = channel.unary_unary(
                '/warp.QueryService/Execute',
                request_serializer=warp__pb2.ExecuteRequest.SerializeToString,
                response_deserializer=warp__pb2.ExecuteResponse.FromString,
                _registered_method=True)


class QueryServiceServicer(object):
    """Native Warp wire protocol: a thin Type-3 JDBC driver talks this
    instead of emulating a foreign database's wire protocol. Stateless per
    call — username/password travel on every request rather than a separate
    session-establishing RPC, keeping the server side simple (no
    session/stream bookkeeping) for this first narrow slice.
    """

    def Execute(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_QueryServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Execute': grpc.unary_unary_rpc_method_handler(
                    servicer.Execute,
                    request_deserializer=warp__pb2.ExecuteRequest.FromString,
                    response_serializer=warp__pb2.ExecuteResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'warp.QueryService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('warp.QueryService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class QueryService(object):
    """Native Warp wire protocol: a thin Type-3 JDBC driver talks this
    instead of emulating a foreign database's wire protocol. Stateless per
    call — username/password travel on every request rather than a separate
    session-establishing RPC, keeping the server side simple (no
    session/stream bookkeeping) for this first narrow slice.
    """

    @staticmethod
    def Execute(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/warp.QueryService/Execute',
            warp__pb2.ExecuteRequest.SerializeToString,
            warp__pb2.ExecuteResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class WarpPeerServiceStub(object):
    """Phase 1a of the parallel execution engine (see the "jazzy-wishing-balloon" design plan):
    a NODE-TO-NODE service, deliberately separate from QueryService above -- that service
    authenticates an END USER (username/password against CredentialStore) for ad-hoc SQL; this one
    authenticates a PEER WARP NODE via mutual TLS (see server/TlsSupport#buildMutualSslContext and
    grpc/WarpPeerGrpcServer), and only ever carries a single partition's already-collected rows for
    one federated-join partition to be matched locally and returned -- never a SQL statement, never
    a connection to an original backend. Deliberately unary (not streaming): this codebase has no
    existing streaming RPC precedent, and a first version mirroring QueryService's own proven
    unary shape is a smaller, safer step than inventing bidirectional streaming from scratch.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.JoinPartition = channel.unary_unary(
                '/warp.WarpPeerService/JoinPartition',
                request_serializer=warp__pb2.JoinPartitionRequest.SerializeToString,
                response_deserializer=warp__pb2.JoinPartitionResponse.FromString,
                _registered_method=True)


class WarpPeerServiceServicer(object):
    """Phase 1a of the parallel execution engine (see the "jazzy-wishing-balloon" design plan):
    a NODE-TO-NODE service, deliberately separate from QueryService above -- that service
    authenticates an END USER (username/password against CredentialStore) for ad-hoc SQL; this one
    authenticates a PEER WARP NODE via mutual TLS (see server/TlsSupport#buildMutualSslContext and
    grpc/WarpPeerGrpcServer), and only ever carries a single partition's already-collected rows for
    one federated-join partition to be matched locally and returned -- never a SQL statement, never
    a connection to an original backend. Deliberately unary (not streaming): this codebase has no
    existing streaming RPC precedent, and a first version mirroring QueryService's own proven
    unary shape is a smaller, safer step than inventing bidirectional streaming from scratch.
    """

    def JoinPartition(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_WarpPeerServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'JoinPartition': grpc.unary_unary_rpc_method_handler(
                    servicer.JoinPartition,
                    request_deserializer=warp__pb2.JoinPartitionRequest.FromString,
                    response_serializer=warp__pb2.JoinPartitionResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'warp.WarpPeerService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('warp.WarpPeerService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class WarpPeerService(object):
    """Phase 1a of the parallel execution engine (see the "jazzy-wishing-balloon" design plan):
    a NODE-TO-NODE service, deliberately separate from QueryService above -- that service
    authenticates an END USER (username/password against CredentialStore) for ad-hoc SQL; this one
    authenticates a PEER WARP NODE via mutual TLS (see server/TlsSupport#buildMutualSslContext and
    grpc/WarpPeerGrpcServer), and only ever carries a single partition's already-collected rows for
    one federated-join partition to be matched locally and returned -- never a SQL statement, never
    a connection to an original backend. Deliberately unary (not streaming): this codebase has no
    existing streaming RPC precedent, and a first version mirroring QueryService's own proven
    unary shape is a smaller, safer step than inventing bidirectional streaming from scratch.
    """

    @staticmethod
    def JoinPartition(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/warp.WarpPeerService/JoinPartition',
            warp__pb2.JoinPartitionRequest.SerializeToString,
            warp__pb2.JoinPartitionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
