"""Corpus part 4: indexes, collection/database administration, validators, cursors, server commands, handshake."""
import datetime

from bson import Int64
from pymongo import ASCENDING, DESCENDING, HASHED, IndexModel

from mongo_corpus import case

D = datetime.datetime


@case("idx_create_list_drop")
def _(e):
    c = e.c
    e.op("list_missing", lambda: list(c.list_indexes()))
    e.cmd("list_missing_cmd", {"listIndexes": "c"})
    c.insert_one({"_id": 1, "a": 1, "b": 2, "c": [1, 2]})
    e.op("list_default", lambda: [dict(i) for i in c.list_indexes()])
    e.op("single", lambda: c.create_index("a"))
    e.op("compound", lambda: c.create_index([("a", 1), ("b", -1)]))
    e.op("named", lambda: c.create_index("b", name="my_b"))
    e.op("unique", lambda: c.create_index("c", unique=True))
    e.op("sparse", lambda: c.create_index("zz", sparse=True))
    e.op("partial", lambda: c.create_index("p", partialFilterExpression={"p": {"$gt": 1}}))
    e.op("ttl", lambda: c.create_index("t", expireAfterSeconds=3600))
    e.op("hashed", lambda: c.create_index([("h", HASHED)]))
    e.op("collation_idx", lambda: c.create_index("s", collation={"locale": "en", "strength": 2}))
    e.op("wildcard", lambda: c.create_index("$**"))
    e.op("text", lambda: c.create_index([("txt", "text")]))
    e.op("2dsphere", lambda: c.create_index([("loc", "2dsphere")]))
    e.op("hidden", lambda: c.create_index("hid", hidden=True))
    e.op("list_after", lambda: [dict(i) for i in c.list_indexes()])
    e.op("index_information", lambda: c.index_information())
    e.op("same_again", lambda: c.create_index("a"))
    e.op("same_key_other_name", lambda: c.create_index("a", name="other"))
    e.op("same_name_other_key", lambda: c.create_index("b", name="a_1"))
    e.op("same_key_other_opts", lambda: c.create_index("a", unique=True))
    e.op("id_index", lambda: c.create_index("_id"))
    e.op("id_unique_false", lambda: c.create_index("_id", unique=False))
    e.op("bad_key_zero", lambda: c.create_index([("x", 0)]))
    e.op("bad_key_value", lambda: c.create_index([("x", "bogus")]))
    e.op("bad_ttl", lambda: c.create_index([("a", 1), ("b", 1)], expireAfterSeconds=10))
    e.op("bad_option", lambda: c.create_index("q", bogusOption=1))
    e.op("empty_key", lambda: c.database.command({"createIndexes": "c", "indexes": [{"key": {}, "name": "e"}]}))
    e.op("no_indexes", lambda: c.database.command({"createIndexes": "c", "indexes": []}))
    e.op("no_name", lambda: c.database.command({"createIndexes": "c", "indexes": [{"key": {"nm": 1}}]}))
    e.op("many", lambda: c.create_indexes([IndexModel("m1"), IndexModel("m2"), IndexModel([("m3", -1)])]))
    e.op("create_on_missing_coll", lambda: e.coll("fresh").create_index("a"))
    e.op("fresh_names", lambda: "fresh" in e.db.list_collection_names())
    e.cmd("raw_create", {"createIndexes": "c", "indexes": [{"key": {"raw": 1}, "name": "raw_1"}]})
    e.cmd("raw_create_dup", {"createIndexes": "c", "indexes": [{"key": {"raw": 1}, "name": "raw_1"}]})
    e.op("drop_by_name", lambda: c.drop_index("a_1"))
    e.op("drop_missing", lambda: c.drop_index("nope_1"))
    e.op("drop_id", lambda: c.drop_index("_id_"))
    e.op("drop_by_key", lambda: c.drop_index([("a", 1), ("b", -1)]))
    e.op("drop_all", lambda: c.drop_indexes())
    e.op("list_end", lambda: [dict(i) for i in c.list_indexes()])
    e.cmd("drop_indexes_star", {"dropIndexes": "c", "index": "*"})
    e.cmd("drop_indexes_missing_coll", {"dropIndexes": "nosuch", "index": "*"})
    e.cmd("drop_indexes_array", {"dropIndexes": "c", "index": ["a_1", "x"]})
    e.cmd("drop_indexes_bad", {"dropIndexes": "c", "index": 1})


@case("idx_unique_enforcement")
def _(e):
    c = e.c
    c.create_index("u", unique=True)
    e.op("ins1", lambda: c.insert_one({"_id": 1, "u": 1}))
    e.op("ins_dup", lambda: c.insert_one({"_id": 2, "u": 1}))
    e.op("ins_missing1", lambda: c.insert_one({"_id": 3}))
    e.op("ins_missing2_dup", lambda: c.insert_one({"_id": 4}))
    e.op("ins_null_dup", lambda: c.insert_one({"_id": 5, "u": None}))
    e.op("ins_numeric_dup", lambda: c.insert_one({"_id": 6, "u": 1.0}))
    e.op("ins_string_ok", lambda: c.insert_one({"_id": 7, "u": "1"}))
    e.op("ins_array_multikey", lambda: c.insert_one({"_id": 8, "u": [10, 11]}))
    e.op("ins_array_overlap", lambda: c.insert_one({"_id": 9, "u": [11, 12]}))
    e.op("ins_many_unordered", lambda: c.insert_many([{"_id": 20, "u": 100}, {"_id": 21, "u": 100}, {"_id": 22, "u": 101}, {"_id": 23, "u": 1}], ordered=False))
    e.op("update_to_dup", lambda: c.update_one({"_id": 7}, {"$set": {"u": 100}}))
    e.op("update_to_free", lambda: c.update_one({"_id": 7}, {"$set": {"u": 200}}))
    e.op("update_self_same", lambda: c.update_one({"_id": 7}, {"$set": {"u": 200}}))
    e.op("insert_freed_key", lambda: c.insert_one({"_id": 30, "u": "1"}))
    e.op("delete_frees", lambda: c.delete_one({"_id": 1}))
    e.op("reuse_after_delete", lambda: c.insert_one({"_id": 31, "u": 1}))
    e.op("replace_dup", lambda: c.replace_one({"_id": 31}, {"u": 100}))
    e.op("fam_dup", lambda: c.find_one_and_update({"_id": 31}, {"$set": {"u": 100}}))
    e.op("upsert_dup", lambda: c.update_one({"zz": 1}, {"$set": {"u": 100}}, upsert=True))
    e.op("bulk_dup", lambda: c.bulk_write([__import__("pymongo").InsertOne({"_id": 40, "u": 400}), __import__("pymongo").InsertOne({"_id": 41, "u": 400})], ordered=False))
    e.state("state")
    c2 = e.coll("c2")
    c2.insert_many([{"_id": 1, "a": 1}, {"_id": 2, "a": 1}])
    e.op("build_unique_on_dups", lambda: c2.create_index("a", unique=True))
    e.op("c2_indexes_after_fail", lambda: sorted(c2.index_information().keys()))
    c2.delete_one({"_id": 2})
    e.op("build_unique_ok", lambda: c2.create_index("a", unique=True))
    e.op("c2_dup_after_build", lambda: c2.insert_one({"a": 1}))
    c3 = e.coll("c3")
    c3.create_index([("a", 1), ("b", 1)], unique=True)
    e.op("comp1", lambda: c3.insert_one({"_id": 1, "a": 1, "b": 1}))
    e.op("comp2", lambda: c3.insert_one({"_id": 2, "a": 1, "b": 2}))
    e.op("comp_dup", lambda: c3.insert_one({"_id": 3, "a": 1, "b": 1}))
    e.op("comp_missing", lambda: c3.insert_one({"_id": 4, "a": 1}))
    e.op("comp_missing_dup", lambda: c3.insert_one({"_id": 5, "a": 1}))
    e.op("comp_parallel_arrays", lambda: c3.insert_one({"_id": 6, "a": [1, 2], "b": [1, 2]}))
    c4 = e.coll("c4")
    c4.create_index("s", unique=True, sparse=True)
    e.op("sparse1", lambda: c4.insert_one({"_id": 1}))
    e.op("sparse2", lambda: c4.insert_one({"_id": 2}))
    e.op("sparse3", lambda: c4.insert_one({"_id": 3, "s": None}))
    e.op("sparse4_dup", lambda: c4.insert_one({"_id": 4, "s": None}))
    c5 = e.coll("c5")
    c5.create_index("p", unique=True, partialFilterExpression={"active": True})
    e.op("partial1", lambda: c5.insert_one({"_id": 1, "p": 1, "active": True}))
    e.op("partial2_inactive", lambda: c5.insert_one({"_id": 2, "p": 1, "active": False}))
    e.op("partial3_dup", lambda: c5.insert_one({"_id": 3, "p": 1, "active": True}))
    c6 = e.coll("c6")
    c6.create_index("s", unique=True, collation={"locale": "en", "strength": 2})
    e.op("coll1", lambda: c6.insert_one({"_id": 1, "s": "abc"}))
    e.op("coll2_case", lambda: c6.insert_one({"_id": 2, "s": "ABC"}))
    c7 = e.coll("c7")
    c7.create_index("a.b", unique=True)
    e.op("dotted1", lambda: c7.insert_one({"_id": 1, "a": {"b": 1}}))
    e.op("dotted_dup", lambda: c7.insert_one({"_id": 2, "a": {"b": 1}}))
    e.op("dotted_arr_dup", lambda: c7.insert_one({"_id": 3, "a": [{"b": 1}, {"b": 2}]}))
    e.op("drop_unique_then_dup", lambda: (c7.drop_index("a.b_1"), c7.insert_one({"_id": 4, "a": {"b": 1}}).inserted_id)[1])


@case("idx_ttl_and_hint")
def _(e):
    c = e.c
    c.create_index("t", expireAfterSeconds=0)
    c.create_index("k")
    e.op("hint_name", lambda: [d["_id"] for d in c.find({}).hint("k_1")])
    e.op("hint_key", lambda: [d["_id"] for d in c.find({}).hint([("k", 1)])])
    e.op("hint_id", lambda: [d["_id"] for d in c.find({}).hint("_id_")])
    e.op("hint_natural", lambda: [d["_id"] for d in c.find({}).hint([("$natural", 1)])])
    e.op("hint_bad", lambda: [d["_id"] for d in c.find({}).hint("bad_1")])
    e.op("hint_count", lambda: c.count_documents({}, hint="k_1"))
    e.op("hint_count_bad", lambda: c.count_documents({}, hint="bad_1"))
    e.cmd("collmod_ttl", {"collMod": "c", "index": {"keyPattern": {"t": 1}, "expireAfterSeconds": 100}})
    e.op("list_after_collmod", lambda: [dict(i) for i in c.list_indexes()])
    e.cmd("collmod_hidden", {"collMod": "c", "index": {"name": "k_1", "hidden": True}})
    e.cmd("collmod_bad_index", {"collMod": "c", "index": {"name": "zz", "hidden": True}})
    c.insert_many([{"_id": 1, "t": D(2000, 1, 1)}, {"_id": 2, "t": D(2999, 1, 1)}, {"_id": 3}, {"_id": 4, "t": "notadate"}])
    e.op("ttl_expired_visible_until_sweep", lambda: c.count_documents({}) >= 3)


@case("admin_collections")
def _(e):
    db = e.db
    e.op("names_empty", lambda: db.list_collection_names())
    e.cmd("create", {"create": "a"})
    e.cmd("create_again", {"create": "a"})
    e.cmd("create_capped", {"create": "cap", "capped": True, "size": 4096, "max": 3})
    e.cmd("create_capped_nosize", {"create": "cap2", "capped": True})
    e.cmd("create_validator", {"create": "val", "validator": {"$jsonSchema": {"bsonType": "object", "required": ["x"]}}})
    e.cmd("create_bad_option", {"create": "bad", "bogus": 1})
    e.cmd("create_view", {"create": "vw", "viewOn": "a", "pipeline": []})
    e.cmd("create_bad_name", {"create": "bad$name"})
    e.cmd("create_empty_name", {"create": ""})
    e.cmd("create_collation", {"create": "coll", "collation": {"locale": "en"}})
    e.cmd("create_bad_validator", {"create": "bv", "validator": 1})
    e.op("names", lambda: sorted(db.list_collection_names()))
    e.cmd("listcollections_shape", {"listCollections": 1}, mask=())
    e.cmd("listcollections_nameonly", {"listCollections": 1, "nameOnly": True})
    e.cmd("listcollections_filter", {"listCollections": 1, "filter": {"name": "a"}, "nameOnly": True})
    e.cmd("listcollections_filter_type", {"listCollections": 1, "filter": {"type": "view"}})
    e.cmd("listcollections_batch", {"listCollections": 1, "nameOnly": True, "cursor": {"batchSize": 1}})
    e.op("options", lambda: {k: v for k, v in db.get_collection("cap").options().items()})
    e.op("options_val", lambda: db.get_collection("val").options())
    e.cmd("listcollections_bad_filter", {"listCollections": 1, "filter": 5})
    e.coll("a").insert_many([{"_id": i} for i in range(3)])
    e.cmd("rename", {"renameCollection": e.dbname + ".a", "to": e.dbname + ".b"}, db="admin")
    e.op("names_after_rename", lambda: sorted(db.list_collection_names()))
    e.op("rename_data", lambda: [d["_id"] for d in db["b"].find({}).sort("_id", 1)])
    e.cmd("rename_missing", {"renameCollection": e.dbname + ".zzz", "to": e.dbname + ".y"}, db="admin")
    e.cmd("rename_target_exists", {"renameCollection": e.dbname + ".b", "to": e.dbname + ".val"}, db="admin")
    e.cmd("rename_drop_target", {"renameCollection": e.dbname + ".b", "to": e.dbname + ".val", "dropTarget": True}, db="admin")
    e.cmd("rename_same", {"renameCollection": e.dbname + ".val", "to": e.dbname + ".val"}, db="admin")
    e.cmd("rename_bad_ns", {"renameCollection": "nodot", "to": "x.y"}, db="admin")
    e.op("rename_method", lambda: db["val"].rename("val2") and 1)
    e.op("names_after", lambda: sorted(db.list_collection_names()))
    e.cmd("drop", {"drop": "val2"})
    e.cmd("drop_again", {"drop": "val2"})
    e.cmd("drop_bad", {"drop": 1})
    e.op("dbstats_keys", lambda: sorted(k for k in db.command("dbStats").keys()))
    e.op("collstats_keys", lambda: sorted(k for k in db.command("collStats", "cap").keys() if k in ("ns", "count", "size", "nindexes", "capped", "ok")))
    e.cmd("collstats_missing", {"collStats": "nosuch"})
    e.cmd("validate", {"validate": "cap"}, mask=())
    e.cmd("validate_missing", {"validate": "nosuch"})
    e.op("dbstats_counts", lambda: {k: db.command("dbStats")[k] for k in ("db", "collections", "objects", "indexes")})
    e.cmd("drop_database", {"dropDatabase": 1})
    e.op("names_after_dropdb", lambda: db.list_collection_names())
    e.cmd("drop_database_again", {"dropDatabase": 1})
    e.op("dbnames_contains", lambda: e.dbname in e.client.list_database_names())


@case("admin_validators")
def _(e):
    db = e.db
    e.cmd("create", {"create": "v", "validator": {"$jsonSchema": {"bsonType": "object", "required": ["name", "age"], "properties": {"name": {"bsonType": "string", "minLength": 2}, "age": {"bsonType": "int", "minimum": 0, "maximum": 150}, "tags": {"bsonType": "array", "uniqueItems": True, "items": {"bsonType": "string"}}}}}})
    c = db["v"]
    e.op("ok", lambda: c.insert_one({"_id": 1, "name": "Al", "age": 30, "tags": ["a", "b"]}))
    e.op("missing_required", lambda: c.insert_one({"_id": 2, "name": "Al"}))
    e.op("wrong_type", lambda: c.insert_one({"_id": 3, "name": "Al", "age": "x"}))
    e.op("min_length", lambda: c.insert_one({"_id": 4, "name": "A", "age": 3}))
    e.op("range", lambda: c.insert_one({"_id": 5, "name": "Al", "age": 200}))
    e.op("unique_items", lambda: c.insert_one({"_id": 6, "name": "Al", "age": 3, "tags": ["a", "a"]}))
    e.op("items_type", lambda: c.insert_one({"_id": 7, "name": "Al", "age": 3, "tags": [1]}))
    e.op("many_unordered", lambda: c.insert_many([{"_id": 10, "name": "Bo", "age": 1}, {"_id": 11}, {"_id": 12, "name": "Cy", "age": 2}], ordered=False))
    e.op("bypass", lambda: c.insert_one({"_id": 13}, bypass_document_validation=True))
    e.op("update_violates", lambda: c.update_one({"_id": 1}, {"$set": {"age": -1}}))
    e.op("update_ok", lambda: c.update_one({"_id": 1}, {"$set": {"age": 31}}))
    e.op("update_bypass", lambda: c.update_one({"_id": 1}, {"$set": {"age": -1}}, bypass_document_validation=True))
    e.op("replace_violates", lambda: c.replace_one({"_id": 1}, {"name": "x"}))
    e.op("fam_violates", lambda: c.find_one_and_update({"_id": 10}, {"$unset": {"name": ""}}))
    e.state("state", c)
    e.cmd("collmod_level_moderate", {"collMod": "v", "validationLevel": "moderate"})
    e.op("moderate_update_invalid_doc_ok", lambda: c.update_one({"_id": 1}, {"$set": {"other": 1}}))
    e.op("moderate_insert_still_validated", lambda: c.insert_one({"_id": 20, "name": "A"}))
    e.cmd("collmod_action_warn", {"collMod": "v", "validationAction": "warn"})
    e.op("warn_allows", lambda: c.insert_one({"_id": 21, "name": "A"}))
    e.cmd("collmod_level_off", {"collMod": "v", "validationLevel": "off"})
    e.cmd("collmod_bad_level", {"collMod": "v", "validationLevel": "bogus"})
    e.cmd("collmod_new_validator", {"collMod": "v", "validator": {"n": {"$gt": 0}}, "validationLevel": "strict", "validationAction": "error"})
    e.op("query_validator_ok", lambda: c.insert_one({"_id": 30, "n": 5}))
    e.op("query_validator_bad", lambda: c.insert_one({"_id": 31, "n": -5}))
    e.op("list_options", lambda: db["v"].options())
    e.cmd("collmod_missing", {"collMod": "nosuch", "validator": {}})
    e.cmd("collmod_unknown", {"collMod": "v", "bogus": 1})
    e.cmd("collmod_empty_validator", {"collMod": "v", "validator": {}})
    e.op("after_empty_validator", lambda: c.insert_one({"_id": 32, "n": -1}))


@case("cursor_lifecycle")
def _(e):
    c = e.c
    c.insert_many([{"_id": i, "v": i} for i in range(1, 21)])
    e.cmd("find", {"find": "c", "sort": {"_id": 1}, "batchSize": 5})
    cid = e.replies["find"]["cursor"]["id"]
    e.cmd("getmore1", {"getMore": cid, "collection": "c", "batchSize": 5})
    e.cmd("getmore_default", {"getMore": cid, "collection": "c"})
    e.cmd("getmore_exhausted", {"getMore": cid, "collection": "c"})
    e.cmd("find2", {"find": "c", "sort": {"_id": 1}, "batchSize": 2})
    c2 = e.replies["find2"]["cursor"]["id"]
    e.cmd("getmore_wrong_coll", {"getMore": c2, "collection": "other"})
    e.cmd("getmore_bad_id_type", {"getMore": 1, "collection": "c"})
    e.cmd("getmore_no_coll", {"getMore": c2})
    e.cmd("getmore_neg_batch", {"getMore": c2, "collection": "c", "batchSize": -1})
    e.cmd("getmore_zero_batch", {"getMore": c2, "collection": "c", "batchSize": 0})
    e.cmd("kill", {"killCursors": "c", "cursors": [c2]})
    e.cmd("kill_again", {"killCursors": "c", "cursors": [c2]})
    e.cmd("getmore_after_kill", {"getMore": c2, "collection": "c"})
    e.cmd("kill_bad", {"killCursors": "c", "cursors": [1]})
    e.cmd("kill_no_cursors", {"killCursors": "c"})
    e.cmd("kill_not_array", {"killCursors": "c", "cursors": 5})
    e.cmd("kill_zero", {"killCursors": "c", "cursors": [Int64(0)]})
    e.cmd("agg", {"aggregate": "c", "pipeline": [{"$sort": {"_id": 1}}], "cursor": {"batchSize": 7}})
    a = e.replies["agg"]["cursor"]["id"]
    e.cmd("agg_getmore", {"getMore": a, "collection": "c", "batchSize": 100})
    e.cmd("agg_getmore_again", {"getMore": a, "collection": "c"})
    e.op("driver_iteration", lambda: [d["_id"] for d in c.find({}, batch_size=3).sort("_id", 1)])
    e.op("driver_limit_batch", lambda: [d["_id"] for d in c.find({}, batch_size=3, limit=7).sort("_id", 1)])
    e.op("driver_skip_batch", lambda: [d["_id"] for d in c.find({}, batch_size=4, skip=15).sort("_id", 1)])
    e.op("driver_close_midway", lambda: (lambda cur: (next(cur), cur.close(), 1)[2])(c.find({}, batch_size=2).sort("_id", 1)))
    e.op("driver_alive", lambda: (lambda cur: (next(cur), cur.alive)[1])(c.find({}, batch_size=2).sort("_id", 1)))
    e.op("driver_exhaust_flag", lambda: len(list(c.find({}, batch_size=6, cursor_type=__import__("pymongo").CursorType.EXHAUST))))
    e.op("driver_batch1", lambda: len(list(c.find({}, batch_size=1))))
    e.op("list_collections_cursor", lambda: len(list(e.db.list_collections())))
    e.op("list_indexes_cursor", lambda: len(list(c.list_indexes())))
    e.cmd("tailable_noncapped", {"find": "c", "tailable": True})
    e.cmd("awaitdata_no_tailable", {"find": "c", "awaitData": True})


@case("server_commands")
def _(e):
    def hello(cmd="hello"):
        r = e.client.admin.command(cmd)
        keep = ("isWritablePrimary", "ismaster", "maxBsonObjectSize", "maxMessageSizeBytes", "maxWriteBatchSize", "logicalSessionTimeoutMinutes", "minWireVersion", "readOnly", "ok")
        return {k: r[k] for k in keep if k in r}
    e.op("hello", lambda: hello("hello"))
    e.op("ismaster", lambda: hello("ismaster"))
    e.op("isMaster", lambda: hello("isMaster"))
    e.op("maxwire_ge_17", lambda: e.client.admin.command("hello")["maxWireVersion"] >= 17)
    e.op("hello_has_localtime", lambda: "localTime" in e.client.admin.command("hello"))
    e.op("hello_compression", lambda: e.client.admin.command({"hello": 1, "compression": ["zlib"]}).get("compression"))
    e.op("hello_compression_none", lambda: e.client.admin.command({"hello": 1, "compression": ["bogus"]}).get("compression"))
    e.op("hello_saslmechs_unknown_user", lambda: e.client.admin.command({"hello": 1, "saslSupportedMechs": "admin.nobody"}).get("saslSupportedMechs"))
    e.cmd("ping", {"ping": 1}, db="admin")
    e.cmd("ping_test_db", {"ping": 1})
    e.op("buildinfo", lambda: {k: v for k, v in e.client.admin.command("buildInfo").items() if k in ("bits", "maxBsonObjectSize", "ok")})
    e.op("buildinfo_version_7", lambda: e.client.admin.command("buildInfo")["version"].startswith("7."))
    e.op("buildinfo_versionarray", lambda: len(e.client.admin.command("buildInfo")["versionArray"]))
    e.cmd("getparameter_fcv", {"getParameter": 1, "featureCompatibilityVersion": 1}, db="admin")
    e.cmd("getparameter_unknown", {"getParameter": 1, "noSuchParam": 1}, db="admin")
    e.op("whatsmyuri", lambda: "you" in e.client.admin.command("whatsmyuri"))
    e.cmd("connectionstatus", {"connectionStatus": 1}, db="admin")
    e.op("listcommands_has", lambda: sorted(c for c in ("find", "insert", "update", "delete", "aggregate", "count", "distinct", "createIndexes", "listCollections", "ping", "hello", "getMore", "killCursors", "findAndModify") if c in e.client.admin.command("listCommands")["commands"]))
    e.op("listcommands_shape", lambda: sorted(e.client.admin.command("listCommands")["commands"]["find"].keys()))
    e.op("serverstatus_keys", lambda: all(k in e.client.admin.command("serverStatus") for k in ("host", "version", "uptime", "connections", "opcounters", "ok")))
    e.op("hostinfo_ok", lambda: e.client.admin.command("hostInfo")["ok"])
    e.op("listdatabases_shape", lambda: sorted(e.client.admin.command("listDatabases")["databases"][0].keys()))
    e.op("listdatabases_has_admin", lambda: {"admin", "local", "config"} <= set(e.client.list_database_names()))
    e.cmd("listdatabases_nameonly", {"listDatabases": 1, "nameOnly": True, "filter": {"name": "admin"}}, db="admin")
    e.cmd("unknown_command", {"fooBar": 1})
    e.cmd("empty_command_name", {"": 1})
    e.cmd("wrong_case", {"Find": "c"})
    e.cmd("endsessions", {"endSessions": []}, db="admin")
    e.op("explain_find_shape", lambda: sorted(e.db.command({"explain": {"find": "c", "filter": {"a": 1}}, "verbosity": "queryPlanner"}).keys()))
    e.op("explain_stage", lambda: e.db.command({"explain": {"find": "c", "filter": {"a": 1}}})["queryPlanner"]["winningPlan"]["stage"])
    e.coll("c").insert_many([{"a": 1}, {"a": 2}])
    e.op("explain_execstats_n", lambda: e.db.command({"explain": {"find": "c", "filter": {"a": 1}}, "verbosity": "executionStats"})["executionStats"]["nReturned"])
    e.cmd("explain_bad", {"explain": 1})
    e.cmd("explain_unknown", {"explain": {"fooBar": 1}})
    e.op("transaction_rejected", lambda: e.db.command({"insert": "c", "documents": [{"a": 9}], "lsid": {"id": __import__("bson").Binary(b"0123456789abcdef", 4)}, "txnNumber": Int64(1), "autocommit": False, "startTransaction": True}))
    e.op("retryable_write_rejected", lambda: e.db.command({"insert": "c", "documents": [{"a": 10}], "lsid": {"id": __import__("bson").Binary(b"0123456789abcdef", 4)}, "txnNumber": Int64(2)}))
    e.op("changestream_rejected", lambda: list(e.coll("c").watch()))
    e.op("session_usage", lambda: (lambda s: (e.coll("c").insert_one({"a": 11}, session=s), s.end_session(), 1)[2])(e.client.start_session()))
    e.op("session_txn_rejected", lambda: (lambda s: (s.start_transaction(), e.coll("c").insert_one({"a": 12}, session=s))[1])(e.client.start_session()))
    e.op("client_info", lambda: e.client.server_info()["ok"])
    def _with_client(**kw):
        cl = __import__("pymongo").MongoClient(e.client.address[0], e.client.address[1], **kw)
        try:
            return cl.get_database(e.dbname)["c"].count_documents({})
        finally:
            cl.close()
    e.op("with_zlib_compression", lambda: _with_client(compressors="zlib"))
    e.op("many_connections", lambda: sum(_with_client() for _ in range(5)))


@case("errors_common")
def _(e):
    c = e.c
    c.insert_one({"_id": 1, "a": 1})
    e.cmd("ns_not_found_drop", {"drop": "nosuch"})
    e.cmd("cmd_not_found", {"nosuchcommand": 1})
    e.cmd("bad_value_limit", {"find": "c", "limit": "x"})
    e.cmd("failed_to_parse_filter_op", {"find": "c", "filter": {"a": {"$bogus": 1}}})
    e.cmd("type_mismatch_filter", {"find": "c", "filter": 1})
    e.cmd("invalid_ns_dollar", {"find": "a$b"})
    e.cmd("invalid_db_name", {"find": "c"}, db="bad db")
    e.cmd("invalid_db_dot", {"find": "c"}, db="a.b")
    e.cmd("invalid_db_empty", {"find": "c"}, db="")
    e.cmd("long_db_name", {"find": "c"}, db="x" * 100)
    e.op("db_with_dash", lambda: e.client["dash-db_" + e.dbname]["c"].insert_one({"_id": 1}).inserted_id)
    e.client.drop_database("dash-db_" + e.dbname)
    e.op("db_case_sensitivity", lambda: e.client[e.dbname.upper()]["c"].insert_one({"_id": 1}).inserted_id)
    e.client.drop_database(e.dbname.upper())
    e.op("index_options_conflict", lambda: (c.create_index("a", name="n1"), c.create_index("a", name="n2"))[1])
    e.op("dup_key_shape", lambda: c.insert_one({"_id": 1}))
    e.op("bulk_error_shape", lambda: c.insert_many([{"_id": 1}, {"_id": 2}, {"_id": 1}], ordered=False))
    e.op("write_concern_error_shape", lambda: e.db.command({"insert": "c", "documents": [{"_id": 100}], "writeConcern": {"w": 3}}))
    e.op("update_error_immutable", lambda: c.update_one({"_id": 1}, {"$set": {"_id": 5}}))
    e.op("update_conflict", lambda: c.update_one({"_id": 1}, {"$set": {"a": 1}, "$inc": {"a": 1}}))
    e.op("update_bad_type", lambda: c.update_one({"_id": 1}, {"$inc": {"a": "x"}}))
    e.op("update_path_not_viable", lambda: c.update_one({"_id": 1}, {"$set": {"a.b": 1}}))
    e.op("pipeline_bad_stage", lambda: list(c.aggregate([{"$nope": {}}])))
    e.op("pipeline_bad_expr", lambda: list(c.aggregate([{"$project": {"x": {"$nope": 1}}}])))
    e.op("pipeline_type_mismatch", lambda: list(c.aggregate([{"$project": {"x": {"$add": ["a", 1]}}}])))
    e.op("divide_by_zero", lambda: list(c.aggregate([{"$project": {"x": {"$divide": [1, 0]}}}])))
    e.op("regex_invalid", lambda: list(c.find({"a": {"$regex": "("}})))
    e.op("sort_key_bad", lambda: list(c.find().sort("$bad", 1)))
    e.op("doc_too_large_client_side", lambda: c.insert_one({"_id": 2, "s": "x" * (17 * 1024 * 1024)}))
    e.op("key_with_null_byte", lambda: c.insert_one({"_id": 3, "a\x00": 1}))
    e.op("invalid_utf8_ok", lambda: c.insert_one({"_id": 4, "s": "퟿"}).inserted_id)
    e.op("unknown_cursor_id", lambda: e.db.command({"getMore": Int64(123456789), "collection": "c"}))
