"""Corpus part 3b: aggregation expression operators, one $project per expression over a single document."""
import datetime

from bson import Decimal128, Int64, ObjectId, Regex, Timestamp

from mongo_corpus import case

D = datetime.datetime
DOC = {"_id": 1, "i": 7, "l": Int64(9), "f": 2.5, "dec": Decimal128("3.25"), "neg": -4, "z": 0, "s": "Hello World", "e": "", "u": "héllo", "n": None, "t": True, "fl": False,
       "arr": [3, 1, 2], "arr2": [1, 2, 3, 4, 5], "docs": [{"a": 1, "b": "x"}, {"a": 2, "b": "y"}, {"a": 3, "b": "x"}], "nested": {"a": {"b": 5}, "arr": [1, 2]}, "d": D(2021, 3, 14, 15, 9, 26, 535000),
       "d2": D(2020, 12, 31, 23, 59, 59), "oid": ObjectId("507f1f77bcf86cd799439011"), "big": 2147483647, "bigl": Int64(9223372036854775807), "str_num": "42", "str_dbl": "3.5", "str_bad": "abc", "dstr": "2021-03-14T15:09:26.535Z",
       "words": ["b", "a", "c"], "mixed": [1, "a", None, True, 2.5], "obj": {"x": 1, "y": 2}, "kv": [{"k": "a", "v": 1}, {"k": "b", "v": 2}], "pairs": [["a", 1], ["b", 2]]}

EXPRS = [
    # arithmetic
    {"$add": ["$i", 1]}, {"$add": ["$i", "$l"]}, {"$add": ["$i", "$f"]}, {"$add": ["$i", "$dec"]}, {"$add": ["$big", 1]}, {"$add": ["$bigl", 1]}, {"$add": ["$i", None]}, {"$add": ["$i", "$nope"]}, {"$add": ["$i", "x"]}, {"$add": ["$d", 1000]}, {"$add": ["$d", "$d2"]},
    {"$add": []}, {"$add": [1]}, {"$add": "$i"}, {"$add": [1, 2, 3, 4]}, {"$subtract": ["$i", 1]}, {"$subtract": ["$d", "$d2"]}, {"$subtract": ["$d", 1000]}, {"$subtract": [1, "$d"]}, {"$subtract": ["$i"]}, {"$subtract": ["$i", None]}, {"$subtract": ["$big", "$neg"]},
    {"$multiply": ["$i", 2]}, {"$multiply": ["$i", "$f"]}, {"$multiply": ["$big", 2]}, {"$multiply": ["$bigl", 2]}, {"$multiply": ["$i", "$dec"]}, {"$multiply": []}, {"$multiply": [2, "x"]}, {"$multiply": ["$i", None]}, {"$multiply": ["$l", "$l"]},
    {"$divide": ["$i", 2]}, {"$divide": ["$i", "$z"]}, {"$divide": ["$i", None]}, {"$divide": ["$dec", 2]}, {"$divide": [1, 3]}, {"$divide": ["$l", 3]}, {"$divide": ["x", 1]}, {"$mod": ["$i", 3]}, {"$mod": ["$neg", 3]}, {"$mod": ["$f", 2]}, {"$mod": ["$i", 0]}, {"$mod": ["$l", 4]}, {"$mod": ["$i", "$dec"]},
    {"$abs": "$neg"}, {"$abs": "$f"}, {"$abs": None}, {"$abs": "x"}, {"$abs": -2147483648}, {"$ceil": "$f"}, {"$ceil": "$i"}, {"$ceil": "$dec"}, {"$ceil": -0.5}, {"$floor": "$f"}, {"$floor": -0.5}, {"$floor": "$dec"}, {"$floor": None},
    {"$round": ["$f", 0]}, {"$round": [2.5]}, {"$round": [3.5]}, {"$round": [1234.567, -2]}, {"$round": [1234.567, 1]}, {"$round": ["$i", -1]}, {"$round": ["$dec", 1]}, {"$round": [-2.5]}, {"$round": ["$f", 200]}, {"$round": ["$f", 1.5]}, {"$round": "$f"},
    {"$trunc": ["$f", 0]}, {"$trunc": [-2.7]}, {"$trunc": [1234.567, -2]}, {"$trunc": ["$dec", 1]}, {"$sqrt": "$i"}, {"$sqrt": 16}, {"$sqrt": "$neg"}, {"$sqrt": None}, {"$sqrt": "$dec"}, {"$pow": [2, 10]}, {"$pow": [2, -1]}, {"$pow": [2.5, 2]}, {"$pow": [0, -1]},
    {"$pow": ["$l", 2]}, {"$pow": [10, 20]}, {"$pow": [-8, 0.5]}, {"$pow": ["$i", 2]}, {"$pow": [2, 31]}, {"$pow": [2, 62]}, {"$pow": [2, 63]}, {"$exp": 0}, {"$exp": 1}, {"$ln": 1}, {"$ln": "$i"}, {"$ln": 0}, {"$ln": "$neg"}, {"$log": [8, 2]}, {"$log": [100, 10]}, {"$log": [8, 1]}, {"$log": [0, 2]}, {"$log10": 1000}, {"$log10": 0},
    {"$sin": 0}, {"$cos": 0}, {"$tan": 0}, {"$asin": 1}, {"$acos": 1}, {"$atan": 1}, {"$atan2": [1, 1]}, {"$sinh": 0}, {"$cosh": 0}, {"$tanh": 0}, {"$degreesToRadians": 180}, {"$radiansToDegrees": 3.14159265358979}, {"$asin": 2}, {"$acosh": 0.5},
    # comparison / boolean / conditional
    {"$eq": ["$i", 7]}, {"$eq": ["$i", 7.0]}, {"$eq": ["$i", "$l"]}, {"$eq": ["$n", None]}, {"$eq": ["$nope", None]}, {"$eq": ["$nope", "$nope"]}, {"$eq": ["$arr", [3, 1, 2]]}, {"$eq": ["$obj", {"x": 1, "y": 2}]}, {"$eq": ["$obj", {"y": 2, "x": 1}]},
    {"$ne": ["$i", 7]}, {"$gt": ["$i", 5]}, {"$gt": ["$s", 5]}, {"$gt": ["$n", 5]}, {"$gt": ["$nope", None]}, {"$gte": ["$i", 7]}, {"$lt": ["$s", "Z"]}, {"$lt": ["$arr", [4]]}, {"$lte": ["$i", "$f"]}, {"$cmp": ["$i", 8]}, {"$cmp": ["a", "a"]}, {"$cmp": ["$n", "$nope"]}, {"$cmp": [[1, 2], [1, 3]]}, {"$gt": ["$dec", "$f"]},
    {"$eq": ["$i"]}, {"$and": [True, 1, "x"]}, {"$and": [True, 0]}, {"$and": []}, {"$or": [0, None, "$nope"]}, {"$or": [0, 1]}, {"$or": []}, {"$not": [True]}, {"$not": ["$n"]}, {"$not": "$i"}, {"$not": [0]}, {"$not": []},
    {"$cond": [True, "y", "n"]}, {"$cond": {"if": {"$gt": ["$i", 5]}, "then": "big", "else": "small"}}, {"$cond": ["$n", 1, 2]}, {"$cond": [1, 2]}, {"$cond": {"if": True, "then": 1}}, {"$cond": {"if": True, "then": 1, "else": 2, "x": 3}},
    {"$ifNull": ["$n", "d"]}, {"$ifNull": ["$i", "d"]}, {"$ifNull": ["$nope", "d"]}, {"$ifNull": ["$n", "$nope", "last"]}, {"$ifNull": ["$n"]}, {"$ifNull": ["$n", None]},
    {"$switch": {"branches": [{"case": {"$gt": ["$i", 10]}, "then": "a"}, {"case": {"$gt": ["$i", 5]}, "then": "b"}], "default": "c"}}, {"$switch": {"branches": [{"case": False, "then": 1}]}}, {"$switch": {"branches": []}}, {"$switch": {"default": 1}}, {"$switch": {"branches": [{"case": True}]}},
    # strings
    {"$concat": ["$s", "!"]}, {"$concat": ["$s", None]}, {"$concat": ["$s", 1]}, {"$concat": []}, {"$concat": ["a", "b", "c"]}, {"$toLower": "$s"}, {"$toUpper": "$u"}, {"$toLower": None}, {"$toUpper": 5}, {"$toLower": "$nope"}, {"$strLenBytes": "$u"}, {"$strLenCP": "$u"}, {"$strLenBytes": "$i"}, {"$strLenCP": None},
    {"$substr": ["$s", 0, 5]}, {"$substr": ["$s", 6, -1]}, {"$substr": ["$s", 20, 2]}, {"$substr": ["$u", 0, 2]}, {"$substr": ["$u", 1, 1]}, {"$substrBytes": ["$u", 0, 2]}, {"$substrBytes": ["$u", 1, 1]}, {"$substrCP": ["$u", 1, 2]}, {"$substrCP": ["$s", -1, 2]}, {"$substr": [12345, 1, 2]}, {"$substr": ["$s", "a", 1]},
    {"$split": ["a,b,,c", ","]}, {"$split": ["$s", " "]}, {"$split": ["$s", ""]}, {"$split": ["$n", ","]}, {"$split": ["abc", "abc"]}, {"$split": [1, ","]}, {"$split": ["", ","]},
    {"$trim": {"input": "  x  "}}, {"$ltrim": {"input": "  x  "}}, {"$rtrim": {"input": "  x  "}}, {"$trim": {"input": "xxaxx", "chars": "x"}}, {"$trim": {"input": None}}, {"$trim": {"input": 5}}, {"$trim": {"chars": "x"}}, {"$trim": "x"},
    {"$indexOfBytes": ["$s", "o"]}, {"$indexOfBytes": ["$s", "o", 5]}, {"$indexOfBytes": ["$s", "o", 5, 7]}, {"$indexOfBytes": ["$s", "zz"]}, {"$indexOfCP": ["$u", "l"]}, {"$indexOfBytes": ["$u", "l"]}, {"$indexOfBytes": ["$n", "o"]}, {"$indexOfBytes": ["$s", ""]}, {"$indexOfBytes": ["$s", 1]},
    {"$replaceOne": {"input": "$s", "find": "o", "replacement": "0"}}, {"$replaceAll": {"input": "$s", "find": "o", "replacement": "0"}}, {"$replaceAll": {"input": "$s", "find": "", "replacement": "-"}}, {"$replaceOne": {"input": None, "find": "o", "replacement": "0"}}, {"$replaceOne": {"input": "$s", "find": 1, "replacement": "0"}},
    {"$strcasecmp": ["$s", "HELLO WORLD"]}, {"$strcasecmp": ["a", "B"]}, {"$strcasecmp": ["$n", "a"]}, {"$strcasecmp": [1, "a"]},
    {"$regexMatch": {"input": "$s", "regex": "^Hello"}}, {"$regexMatch": {"input": "$s", "regex": "hello", "options": "i"}}, {"$regexMatch": {"input": "$s", "regex": "^x"}}, {"$regexMatch": {"input": None, "regex": "x"}}, {"$regexMatch": {"input": "$s", "regex": None}}, {"$regexMatch": {"input": 1, "regex": "x"}},
    {"$regexFind": {"input": "$s", "regex": "o (W)"}}, {"$regexFind": {"input": "$s", "regex": "zz"}}, {"$regexFindAll": {"input": "$s", "regex": "o"}}, {"$regexFindAll": {"input": "$s", "regex": "(l)(l)?"}}, {"$regexFind": {"input": "$u", "regex": "l+"}}, {"$regexFindAll": {"input": "aaa", "regex": "a*?"}},
    {"$regexMatch": {"input": "$s", "regex": Regex("^hello", "i")}}, {"$regexMatch": {"input": "$s", "regex": "["}}, {"$regexFind": {"input": "$s"}}, {"$regexMatch": {"input": "a", "regex": "a", "options": "q"}},
    # arrays
    {"$size": "$arr"}, {"$size": "$i"}, {"$size": "$n"}, {"$size": "$nope"}, {"$size": []}, {"$arrayElemAt": ["$arr", 0]}, {"$arrayElemAt": ["$arr", -1]}, {"$arrayElemAt": ["$arr", 5]}, {"$arrayElemAt": ["$arr", -5]}, {"$arrayElemAt": ["$n", 0]}, {"$arrayElemAt": ["$arr", 1.5]}, {"$arrayElemAt": ["$arr", "a"]}, {"$arrayElemAt": ["$i", 0]},
    {"$first": "$arr"}, {"$last": "$arr"}, {"$first": []}, {"$first": "$n"}, {"$first": "$i"}, {"$in": [2, "$arr"]}, {"$in": [9, "$arr"]}, {"$in": ["$i", "$arr"]}, {"$in": [2, "$i"]}, {"$in": [2, None]}, {"$in": [[1], [[1], 2]]}, {"$in": [2.0, "$arr"]},
    {"$concatArrays": ["$arr", [9]]}, {"$concatArrays": ["$arr", "$n"]}, {"$concatArrays": ["$arr", "$i"]}, {"$concatArrays": []}, {"$concatArrays": ["$arr", "$arr"]}, {"$reverseArray": "$arr"}, {"$reverseArray": "$n"}, {"$reverseArray": "$i"}, {"$reverseArray": []},
    {"$slice": ["$arr2", 2]}, {"$slice": ["$arr2", -2]}, {"$slice": ["$arr2", 1, 2]}, {"$slice": ["$arr2", -3, 2]}, {"$slice": ["$arr2", 10]}, {"$slice": ["$arr2", 0]}, {"$slice": ["$arr2", 1, 0]}, {"$slice": ["$arr2", 1, -1]}, {"$slice": ["$n", 1]}, {"$slice": ["$i", 1]}, {"$slice": ["$arr2", "a"]}, {"$slice": ["$arr2", 1.5]},
    {"$range": [0, 5]}, {"$range": [0, 10, 3]}, {"$range": [5, 0, -2]}, {"$range": [0, 5, 0]}, {"$range": [0, 1.5]}, {"$range": ["a", 1]}, {"$range": [5, 0]}, {"$range": [0, 0]}, {"$indexOfArray": ["$arr", 2]}, {"$indexOfArray": ["$arr", 9]}, {"$indexOfArray": ["$arr2", 3, 1]}, {"$indexOfArray": ["$arr2", 3, 3]}, {"$indexOfArray": ["$n", 1]}, {"$indexOfArray": ["$i", 1]},
    {"$isArray": "$arr"}, {"$isArray": "$i"}, {"$isArray": [[1]]}, {"$isArray": "$nope"}, {"$arrayToObject": "$kv"}, {"$arrayToObject": "$pairs"}, {"$arrayToObject": []}, {"$arrayToObject": "$n"}, {"$arrayToObject": [["a"]]}, {"$arrayToObject": [{"k": 1, "v": 2}]}, {"$arrayToObject": [{"a": 1}]}, {"$arrayToObject": [1]},
    {"$objectToArray": "$obj"}, {"$objectToArray": "$n"}, {"$objectToArray": "$i"}, {"$objectToArray": {}}, {"$mergeObjects": ["$obj", {"z": 3}]}, {"$mergeObjects": ["$obj", None]}, {"$mergeObjects": []}, {"$mergeObjects": ["$obj", "$i"]}, {"$mergeObjects": [{"a": 1}, {"a": 2}]},
    {"$map": {"input": "$arr", "as": "x", "in": {"$multiply": ["$$x", 2]}}}, {"$map": {"input": "$arr", "in": {"$add": ["$$this", 1]}}}, {"$map": {"input": "$n", "as": "x", "in": 1}}, {"$map": {"input": "$i", "as": "x", "in": 1}}, {"$map": {"input": "$arr", "as": "x"}}, {"$map": {"as": "x", "in": 1}},
    {"$map": {"input": "$docs", "as": "d", "in": "$$d.a"}}, {"$map": {"input": "$arr", "as": "X", "in": 1}}, {"$map": {"input": [], "as": "x", "in": 1}}, {"$map": {"input": "$arr", "as": "x", "in": "$$y"}},
    {"$filter": {"input": "$arr", "as": "x", "cond": {"$gt": ["$$x", 1]}}}, {"$filter": {"input": "$arr", "cond": {"$gt": ["$$this", 1]}}}, {"$filter": {"input": "$arr", "as": "x", "cond": {"$gt": ["$$x", 0]}, "limit": 2}}, {"$filter": {"input": "$docs", "as": "d", "cond": {"$eq": ["$$d.b", "x"]}}},
    {"$filter": {"input": "$n", "as": "x", "cond": True}}, {"$filter": {"input": "$i", "as": "x", "cond": True}}, {"$filter": {"input": "$arr", "as": "x"}}, {"$filter": {"input": "$arr", "as": "x", "cond": True, "limit": 0}}, {"$filter": {"input": "$arr", "cond": True, "limit": "a"}},
    {"$reduce": {"input": "$arr", "initialValue": 0, "in": {"$add": ["$$value", "$$this"]}}}, {"$reduce": {"input": "$words", "initialValue": "", "in": {"$concat": ["$$value", "$$this"]}}}, {"$reduce": {"input": "$n", "initialValue": 0, "in": 1}}, {"$reduce": {"input": "$i", "initialValue": 0, "in": 1}},
    {"$reduce": {"input": "$arr", "initialValue": [], "in": {"$concatArrays": ["$$value", ["$$this"]]}}}, {"$reduce": {"input": "$arr", "in": 1}}, {"$reduce": {"input": [], "initialValue": "empty", "in": 1}},
    {"$zip": {"inputs": ["$arr", "$words"]}}, {"$zip": {"inputs": ["$arr", ["a"]], "useLongestLength": True}}, {"$zip": {"inputs": ["$arr", ["a"]], "useLongestLength": True, "defaults": [0, "z"]}}, {"$zip": {"inputs": ["$n", "$arr"]}}, {"$zip": {"inputs": []}}, {"$zip": {"inputs": ["$i"]}},
    {"$sortArray": {"input": "$arr", "sortBy": 1}}, {"$sortArray": {"input": "$arr", "sortBy": -1}}, {"$sortArray": {"input": "$docs", "sortBy": {"b": 1, "a": -1}}}, {"$sortArray": {"input": "$mixed", "sortBy": 1}}, {"$sortArray": {"input": "$n", "sortBy": 1}}, {"$sortArray": {"input": "$i", "sortBy": 1}},
    {"$firstN": {"input": "$arr2", "n": 2}}, {"$lastN": {"input": "$arr2", "n": 2}}, {"$maxN": {"input": "$arr2", "n": 2}}, {"$minN": {"input": "$arr2", "n": 2}}, {"$firstN": {"input": "$arr2", "n": 0}}, {"$firstN": {"input": "$n", "n": 1}}, {"$maxN": {"input": "$mixed", "n": 2}},
    {"$setUnion": ["$arr", [3, 4]]}, {"$setUnion": ["$arr", "$n"]}, {"$setUnion": ["$arr", "$i"]}, {"$setUnion": []}, {"$setUnion": [[1, 1, 2]]}, {"$setIntersection": ["$arr", [3, 4]]}, {"$setIntersection": ["$arr", "$n"]}, {"$setDifference": ["$arr", [3]]}, {"$setDifference": ["$arr", "$n"]}, {"$setEquals": ["$arr", [1, 2, 3]]},
    {"$setEquals": ["$arr", [1, 2]]}, {"$setEquals": ["$arr"]}, {"$setIsSubset": [[1], "$arr"]}, {"$setIsSubset": ["$arr", [1]]}, {"$setIsSubset": ["$n", [1]]}, {"$anyElementTrue": [[0, 1]]}, {"$anyElementTrue": [[0, None]]}, {"$anyElementTrue": [[]]}, {"$allElementsTrue": [[1, 2]]}, {"$allElementsTrue": [[1, 0]]}, {"$allElementsTrue": [[]]}, {"$anyElementTrue": "$i"},
    {"$sum": "$arr"}, {"$sum": ["$i", "$l"]}, {"$sum": "$i"}, {"$sum": "$mixed"}, {"$avg": "$arr"}, {"$avg": "$mixed"}, {"$avg": "$n"}, {"$avg": []}, {"$max": "$arr"}, {"$max": ["$i", "$s"]}, {"$max": "$mixed"}, {"$min": "$arr"}, {"$min": []}, {"$min": ["$n", 1]}, {"$stdDevPop": "$arr"}, {"$stdDevSamp": "$arr"}, {"$stdDevSamp": [1]}, {"$stdDevPop": "$n"},
    # objects / type / conversion
    {"$getField": "i"}, {"$getField": {"field": "i", "input": "$$ROOT"}}, {"$getField": {"field": "a", "input": "$obj"}}, {"$getField": {"field": "x", "input": "$obj"}}, {"$getField": {"field": "nope", "input": "$obj"}}, {"$getField": {"field": 1, "input": "$obj"}}, {"$getField": {"field": "x", "input": "$n"}},
    {"$setField": {"field": "z", "input": "$obj", "value": 3}}, {"$setField": {"field": "x", "input": "$obj", "value": "$$REMOVE"}}, {"$unsetField": {"field": "x", "input": "$obj"}}, {"$setField": {"field": "z", "input": "$n", "value": 1}}, {"$setField": {"field": "z", "input": "$i", "value": 1}},
    {"$literal": "$i"}, {"$literal": {"$add": [1, 2]}}, {"$literal": [1, "$i"]}, {"$let": {"vars": {"a": "$i", "b": 2}, "in": {"$add": ["$$a", "$$b"]}}}, {"$let": {"vars": {"a": 1}, "in": {"$let": {"vars": {"a": 2}, "in": "$$a"}}}}, {"$let": {"vars": {}, "in": 1}}, {"$let": {"in": 1}}, {"$let": {"vars": {"A": 1}, "in": "$$A"}},
    {"$type": "$i"}, {"$type": "$l"}, {"$type": "$f"}, {"$type": "$dec"}, {"$type": "$s"}, {"$type": "$n"}, {"$type": "$nope"}, {"$type": "$arr"}, {"$type": "$obj"}, {"$type": "$t"}, {"$type": "$d"}, {"$type": "$oid"}, {"$type": [1, 2]}, {"$isNumber": "$i"}, {"$isNumber": "$s"}, {"$isNumber": "$dec"}, {"$isNumber": "$nope"},
    {"$toInt": "$str_num"}, {"$toInt": "$f"}, {"$toInt": "$dec"}, {"$toInt": "$l"}, {"$toInt": "$bigl"}, {"$toInt": "$t"}, {"$toInt": "$s"}, {"$toInt": "$str_dbl"}, {"$toInt": "$n"}, {"$toInt": "$d"}, {"$toInt": "$nope"}, {"$toInt": "  42"}, {"$toInt": "0x1A"}, {"$toInt": 1e20},
    {"$toLong": "$str_num"}, {"$toLong": "$f"}, {"$toLong": "$d"}, {"$toLong": "$t"}, {"$toLong": "$str_bad"}, {"$toDouble": "$str_num"}, {"$toDouble": "$str_dbl"}, {"$toDouble": "$i"}, {"$toDouble": "$t"}, {"$toDouble": "$d"}, {"$toDouble": "$str_bad"}, {"$toDouble": "$dec"}, {"$toDouble": "Infinity"}, {"$toDouble": "NaN"},
    {"$toDecimal": "$str_num"}, {"$toDecimal": "$f"}, {"$toDecimal": "$i"}, {"$toDecimal": "$t"}, {"$toDecimal": "$d"}, {"$toDecimal": "$str_bad"}, {"$toDecimal": "1e5"}, {"$toDecimal": 0.1},
    {"$toString": "$i"}, {"$toString": "$l"}, {"$toString": "$f"}, {"$toString": "$dec"}, {"$toString": "$t"}, {"$toString": "$d"}, {"$toString": "$oid"}, {"$toString": "$n"}, {"$toString": "$arr"}, {"$toString": "$obj"}, {"$toString": 1e20}, {"$toString": 0.1}, {"$toString": 100.0}, {"$toString": -0.0}, {"$toString": 1e-7}, {"$toString": 123456789012345.0},
    {"$toBool": "$i"}, {"$toBool": 0}, {"$toBool": "$s"}, {"$toBool": "$e"}, {"$toBool": "$n"}, {"$toBool": "$arr"}, {"$toBool": "$dec"}, {"$toBool": "$nope"}, {"$toBool": "false"},
    {"$toDate": "$l"}, {"$toDate": "$f"}, {"$toDate": "$dstr"}, {"$toDate": "$oid"}, {"$toDate": "$d"}, {"$toDate": "$str_bad"}, {"$toDate": "$t"}, {"$toDate": "2021-03-14"}, {"$toDate": 0}, {"$toDate": "$dec"}, {"$toObjectId": "507f1f77bcf86cd799439011"}, {"$toObjectId": "$str_bad"}, {"$toObjectId": "$oid"}, {"$toObjectId": "$i"},
    {"$convert": {"input": "$str_num", "to": "int"}}, {"$convert": {"input": "$str_bad", "to": "int"}}, {"$convert": {"input": "$str_bad", "to": "int", "onError": -1}}, {"$convert": {"input": "$n", "to": "int"}}, {"$convert": {"input": "$n", "to": "int", "onNull": 0}}, {"$convert": {"input": "$nope", "to": "int", "onNull": 0}},
    {"$convert": {"input": "$i", "to": "string"}}, {"$convert": {"input": "$i", "to": 2}}, {"$convert": {"input": "$i", "to": "bogus"}}, {"$convert": {"input": "$i"}}, {"$convert": {"to": "int"}}, {"$convert": {"input": "$i", "to": {"type": "double"}}}, {"$convert": {"input": "$i", "to": "bool"}}, {"$convert": {"input": "$str_num", "to": "decimal"}},
    {"$convert": {"input": "$i", "to": "objectId", "onError": "bad"}}, {"$convert": {"input": "$f", "to": "int", "onError": "err"}}, {"$convert": {"input": "$big", "to": "int"}}, {"$convert": {"input": "$bigl", "to": "int", "onError": "overflow"}}, {"$convert": {"input": "$i", "to": "date"}}, {"$convert": {"input": "$i", "to": "array"}},
    # dates
    {"$year": "$d"}, {"$month": "$d"}, {"$dayOfMonth": "$d"}, {"$hour": "$d"}, {"$minute": "$d"}, {"$second": "$d"}, {"$millisecond": "$d"}, {"$dayOfWeek": "$d"}, {"$dayOfYear": "$d"}, {"$week": "$d"}, {"$isoWeek": "$d"}, {"$isoWeekYear": "$d"}, {"$isoDayOfWeek": "$d"},
    {"$year": "$n"}, {"$year": "$nope"}, {"$year": "$i"}, {"$year": "$oid"}, {"$year": {"date": "$d", "timezone": "America/New_York"}}, {"$hour": {"date": "$d", "timezone": "+05:30"}}, {"$hour": {"date": "$d", "timezone": "Asia/Kolkata"}}, {"$dayOfMonth": {"date": "$d2", "timezone": "Australia/Sydney"}}, {"$year": {"date": "$d", "timezone": "Bogus/Zone"}},
    {"$week": "$d2"}, {"$isoWeek": "$d2"}, {"$isoWeekYear": "$d2"}, {"$dayOfWeek": "$d2"}, {"$dayOfYear": "$d2"}, {"$year": {"date": "$d", "bogus": 1}}, {"$year": {"timezone": "UTC"}},
    {"$dateToString": {"date": "$d"}}, {"$dateToString": {"date": "$d", "format": "%Y-%m-%d"}}, {"$dateToString": {"date": "$d", "format": "%H:%M:%S.%L %j %w %u %U %V %G %%"}}, {"$dateToString": {"date": "$d", "format": "%Y", "timezone": "Asia/Tokyo"}}, {"$dateToString": {"date": "$d", "timezone": "Asia/Tokyo"}},
    {"$dateToString": {"date": "$d", "format": "%z %Z", "timezone": "America/New_York"}}, {"$dateToString": {"date": "$n"}}, {"$dateToString": {"date": "$n", "onNull": "none"}}, {"$dateToString": {"date": "$d", "format": "%Q"}}, {"$dateToString": {"format": "%Y"}}, {"$dateToString": {"date": "$d", "format": "%"}}, {"$dateToString": {"date": "$i"}}, {"$dateToString": {"date": "$oid", "format": "%Y"}},
    {"$dateFromString": {"dateString": "$dstr"}}, {"$dateFromString": {"dateString": "2021-03-14"}}, {"$dateFromString": {"dateString": "2021-03-14T15:09:26"}}, {"$dateFromString": {"dateString": "2021-03-14T15:09:26+02:00"}}, {"$dateFromString": {"dateString": "2021-03-14 15:09", "timezone": "America/New_York"}},
    {"$dateFromString": {"dateString": "14/03/2021", "format": "%d/%m/%Y"}}, {"$dateFromString": {"dateString": "bad"}}, {"$dateFromString": {"dateString": "bad", "onError": "x"}}, {"$dateFromString": {"dateString": None}}, {"$dateFromString": {"dateString": None, "onNull": "n"}}, {"$dateFromString": {"dateString": 5}}, {"$dateFromString": {}},
    {"$dateFromParts": {"year": 2021, "month": 3, "day": 14}}, {"$dateFromParts": {"year": 2021, "month": 14, "day": 35, "hour": 25}}, {"$dateFromParts": {"year": 2021}}, {"$dateFromParts": {"isoWeekYear": 2021, "isoWeek": 10, "isoDayOfWeek": 3}}, {"$dateFromParts": {"year": 2021, "hour": 3, "timezone": "America/New_York"}}, {"$dateFromParts": {"month": 3}}, {"$dateFromParts": {"year": None}},
    {"$dateFromParts": {"year": 20000}}, {"$dateFromParts": {"year": 2021, "month": "a"}}, {"$dateToParts": {"date": "$d"}}, {"$dateToParts": {"date": "$d", "iso8601": True}}, {"$dateToParts": {"date": "$d", "timezone": "Asia/Tokyo"}}, {"$dateToParts": {"date": "$n"}}, {"$dateToParts": {}},
    {"$dateAdd": {"startDate": "$d", "unit": "day", "amount": 1}}, {"$dateAdd": {"startDate": "$d", "unit": "month", "amount": 1}}, {"$dateAdd": {"startDate": "$d2", "unit": "month", "amount": 2}}, {"$dateAdd": {"startDate": "$d", "unit": "year", "amount": -1}}, {"$dateAdd": {"startDate": "$d", "unit": "hour", "amount": 30}}, {"$dateAdd": {"startDate": "$d", "unit": "quarter", "amount": 1}},
    {"$dateAdd": {"startDate": "$d", "unit": "week", "amount": 1}}, {"$dateAdd": {"startDate": "$d", "unit": "millisecond", "amount": 5}}, {"$dateAdd": {"startDate": "$d", "unit": "bogus", "amount": 1}}, {"$dateAdd": {"startDate": "$d", "unit": "day", "amount": 1.5}}, {"$dateAdd": {"startDate": "$n", "unit": "day", "amount": 1}}, {"$dateAdd": {"startDate": "$d", "unit": "day"}},
    {"$dateAdd": {"startDate": "$d", "unit": "day", "amount": 1, "timezone": "America/New_York"}}, {"$dateSubtract": {"startDate": "$d", "unit": "day", "amount": 1}}, {"$dateSubtract": {"startDate": "$d", "unit": "month", "amount": 13}},
    {"$dateDiff": {"startDate": "$d2", "endDate": "$d", "unit": "day"}}, {"$dateDiff": {"startDate": "$d2", "endDate": "$d", "unit": "month"}}, {"$dateDiff": {"startDate": "$d2", "endDate": "$d", "unit": "year"}}, {"$dateDiff": {"startDate": "$d2", "endDate": "$d", "unit": "hour"}}, {"$dateDiff": {"startDate": "$d2", "endDate": "$d", "unit": "week"}}, {"$dateDiff": {"startDate": "$d2", "endDate": "$d", "unit": "quarter"}},
    {"$dateDiff": {"startDate": "$d", "endDate": "$d2", "unit": "day"}}, {"$dateDiff": {"startDate": "$d2", "endDate": "$d", "unit": "millisecond"}}, {"$dateDiff": {"startDate": "$d2", "endDate": "$d", "unit": "second"}}, {"$dateDiff": {"startDate": "$d2", "endDate": "$d", "unit": "minute"}}, {"$dateDiff": {"startDate": "$n", "endDate": "$d", "unit": "day"}}, {"$dateDiff": {"startDate": "$d", "endDate": "$d", "unit": "bogus"}},
    {"$dateDiff": {"startDate": "$d2", "endDate": "$d", "unit": "week", "startOfWeek": "monday"}}, {"$dateTrunc": {"date": "$d", "unit": "day"}}, {"$dateTrunc": {"date": "$d", "unit": "hour"}}, {"$dateTrunc": {"date": "$d", "unit": "month"}}, {"$dateTrunc": {"date": "$d", "unit": "year"}}, {"$dateTrunc": {"date": "$d", "unit": "week"}}, {"$dateTrunc": {"date": "$d", "unit": "week", "startOfWeek": "monday"}},
    {"$dateTrunc": {"date": "$d", "unit": "quarter"}}, {"$dateTrunc": {"date": "$d", "unit": "minute", "binSize": 15}}, {"$dateTrunc": {"date": "$d", "unit": "second"}}, {"$dateTrunc": {"date": "$d", "unit": "millisecond", "binSize": 100}}, {"$dateTrunc": {"date": "$n", "unit": "day"}}, {"$dateTrunc": {"date": "$d", "unit": "bogus"}}, {"$dateTrunc": {"unit": "day"}},
    {"$dateTrunc": {"date": "$d", "unit": "day", "timezone": "America/New_York"}}, {"$add": ["$d", {"$multiply": [24, 60, 60, 1000]}]}, {"$toDate": {"$add": ["$d", 1]}},
    # misc / errors
    {"$foo": 1}, {"$and": 1}, {"$literal": 1, "$add": 1}, {"a": {"$add": [1, 2]}}, {"$bsonSize": "$obj"}, {"$bsonSize": "$n"}, {"$bsonSize": "$i"}, {"$binarySize": "$s"}, {"$binarySize": "$n"}, {"$rand": {}}, {"$sampleRate": 0.5}, {"$meta": "textScore"}, {"$toHashedIndexKey": "$i"},
    "$i", "$s", "$nested.a.b", "$nested.arr", "$docs.a", "$docs.b", "$docs.zz", "$arr.0", "$nope", "$nested.nope.x", "$$ROOT.i", "$$CURRENT.s", "$$NOW", "$$nope", "$", "$$", "$i.x", "plain", 5, None, True, [1, "$i", {"a": "$s"}], {"a": "$i", "b": {"c": "$s"}}, {"a": {"$literal": 1}, "$db": 1},
]


def _chunks(seq, n):
    return [seq[i:i + n] for i in range(0, len(seq), n)]


for _i, _chunk in enumerate(_chunks(EXPRS, 40)):
    def _make(chunk, i):
        @case("expr_%02d" % i)
        def _(e):
            c = e.c
            c.insert_one(DOC)
            for j, ex in enumerate(chunk):
                e.agg("e%02d" % j, c, [{"$project": {"_id": 0, "r": ex}}], mask=())
        return _
    _make(_chunk, _i)
