"""Documented divergences of Warp's gremlinwire from the reference Gremlin Server (Apache TinkerPop 3.8 with TinkerGraph).
Every entry has a reason; the replay tests skip or relax exactly these and nothing else.

* SKIP: cases that are not compared at all (with why).
* EVAL_ONLY_STATUS / BC_ONLY_STATUS: only the status code is compared (the answer differs in content for the stated reason).
Error MESSAGES are never compared (they are Groovy/Java exception texts of the reference); status codes are.
"""

SKIP = {
    "path_131": "match() (declarative pattern matching) is not implemented; Warp answers 597/599.",
    "lang_048": "a Groovy GString result (\"x${1+1}y\") makes the reference fail serialization (599); Warp evaluates interpolation to a plain string.",
    "errors_033": "string element ids are supported (Cosmos-style ids); TinkerGraph's Long id manager rejects g.V('x') with 597.",
}
BC_SKIP = {
    "src_037": "the reference's GraphSON bytecode reader turns P.inside(a, b) into an inclusive-lower-bound range (27 is included for inside(27,35)) while the "
               "script form is exclusive; Warp implements inside() as documented (exclusive on both ends) in both forms.",
}
EVAL_ONLY_STATUS = {}
BC_ONLY_STATUS = {}

# general, documented differences that are not tied to one corpus case:
GENERAL = [
    "Element ids generated by Warp come from a Postgres sequence (1, 2, 3, ...) while TinkerGraph hands out ids from one counter shared with "
    "vertex properties; VertexProperty ids are synthesised from (vertex, key, position) and differ from TinkerGraph's counter.",
    "Error message TEXTS are those of Warp's interpreter, not Groovy's; status codes are equal.",
    "Groovy is not embedded: the script language is a documented subset (literals, variables, arithmetic, lists/maps, closures, if/for/while, def, "
    "method chains) -- classes, imports, string methods beyond the common ones and Groovy-only syntax are script evaluation errors (597).",
    "Graph transactions are not supported (auto-commit), like TinkerGraph: graph.tx().commit() fails with 597.",
    "Lambdas sent as g:Lambda are evaluated by the same subset interpreter.",
    "explain(), profile(), subgraph(), match() and the OLAP steps are not implemented (597/599).",
]


def skip_reason(name):
    return SKIP.get(name)


def eval_divergence(name, gold, got):
    """True when this case's eval answer is a known divergence; a status-only comparison is done for EVAL_ONLY_STATUS cases."""
    if name in EVAL_ONLY_STATUS:
        return gold["code"] == got["code"]
    return False


def bc_divergence(name, gold, got):
    if name in BC_SKIP:
        return True
    if name in BC_ONLY_STATUS:
        return gold["code"] == got["code"]
    return False
