-- Real per-engine differences from ddl/postgres/sqswire_queue_table.sql:
--   BIGSERIAL -> NUMBER GENERATED BY DEFAULT AS IDENTITY (Oracle 12c+ real identity-column
--     syntax; query logic uses JDBC's standard getGeneratedKeys(), not RETURNING INTO -- see
--     SqswireDialect's own javadoc for why this project chose the portable JDBC API over
--     Oracle's own real, but Oracle-specific, OraclePreparedStatement.registerReturnParameter)
--   TEXT -> VARCHAR2(255) for receipt_handle/message_group_id/dedup_id, CLOB for body (real
--     message payloads can be large)
--   TIMESTAMPTZ -> TIMESTAMP WITH TIME ZONE
-- Real, disclosed gap: no IF NOT EXISTS at all pre-23c, same real mitigating factor as every
-- other ddl/oracle/*.sql file in this project.
-- ### table
CREATE TABLE ${table} (
    msg_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    receipt_handle VARCHAR2(255),
    vt TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    enqueued_at TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    read_ct NUMBER DEFAULT 0 NOT NULL,
    body CLOB NOT NULL,
    message_group_id VARCHAR2(255),
    dedup_id VARCHAR2(255)
)
-- ### index_vt
CREATE INDEX ${table}_vt_idx ON ${table} (vt)
-- ### index_dedup
CREATE INDEX ${table}_dedup_idx ON ${table} (dedup_id, enqueued_at)
